### ISSUE TITLE
Go to next input element on enter

### ISSUE THREAD

**Issue by JLambertazzo** [JLambertazzo/ListExtender#11]
Right now on enter the list will be unfocused, we want to instead focus the next input element in the list.

**Comment by MansiAyer** [comment]
Hi, I'd like to attempt to solve this, but I'm not sure if I understand it correctly. I tried the demo on https://www.julienbl.me/ListExtender/ so does this issue mean the part where after adding a new element the focus is not on the input box?
If I've got it wrong, could you please explain this issue to me a bit more?

**Comment by JLambertazzo** [comment]
Hey, if you're interested in this I'd be happy to assign you! When you're typing in an input box and you click tab on your keyboard, you'll see that the focus shifts from the current input to the next in the list. We're just looking to have that same behaviour when enter is pressed instead of tab.

**Comment by MansiAyer** [comment]
Okay, got it. I'm not very good at this but I'll fork the project and give it my best shot, if I am able to work it out then I'll get back to you. Thanks for the opportunity!

**Comment by JLambertazzo** [comment]
Sounds great, this issue is all yours. Good luck! 🚀

**Comment by MansiAyer** [comment]
I think I have fixed all possible issues this time, could you please take a look and lmk if I've missed anything? Live is again at https://listextender.mansimansi.repl.co/

Also when I was comparing the current live example at https://www.julienbl.me/ListExtender/ with my copy, I noticed an issue with the "key" values being assigned to list items. This doesn't affect how the ordered list looks on the page, it's just in the keys. Idk whether this affects functionality in any way, but these are the details:

Steps to recreate: 
When I start typing in the input box, a second input is added to the list. If I then clear what I was typing and then click outside the input box or hit enter, the old input box is deleted, but an input box is added to the list count. This skews the key value in the list items.

Screenshots:
Initial html and console
![image](https://user-images.githubusercontent.com/42694815/137041275-9cd3831f-bbdb-4e2d-abdc-b00d4b7fac32.png)
![image](https://user-images.githubusercontent.com/42694815/137041241-c907ca14-87f9-4dfb-a258-e1dd1eebb909.png)

After typing, then deleting typed text, and focusout/enter
![image](https://user-images.githubusercontent.com/42694815/137040678-e696e002-c0c7-40b2-999a-a3af12e678a5.png)
![image](https://user-images.githubusercontent.com/42694815/137041100-cfe70a7d-7b70-49d3-b46e-e8c4a4ff9e83.png)

**Comment by JLambertazzo** [comment]
Issue closed thanks to contribution from @MansiAyer 🎉
