### ISSUE TITLE
Key attribute of list elements does not account for deleted entries

### ISSUE THREAD

**Issue by JLambertazzo** [JLambertazzo/ListExtender#16]
When an item is deleted from the middle of the list, say the following list:
1. item1
2. item2 <- this one will be removed
3. item3
The resulting list is
1. item1
2. item3 <- this element still has key=3, should be key=2

**Comment by theyup12** [comment]
May I work on it ?

**Comment by yahya-cloud** [comment]
hello @JLambertazzo, i have made this enhancement although i have not been 
assigned this issue but can i still make the PR?

**Comment by yahya-cloud** [comment]
hello @JLambertazzo,  can you please assign me this issue?

**Comment by JLambertazzo** [comment]
This issue is back up for grabs!

**Comment by weisintai** [comment]
@JLambertazzo I have solved this issue, please assign me to this issue!
