### ISSUE TITLE
Indented Lists

### ISSUE THREAD

**Issue by JLambertazzo** [JLambertazzo/ListExtender#54]
When editing an element, pressing tab should nest the element in a sub-list and shift+tab should remove one level of nesting if one exists.

Expected behaviour:
* One
* Two
* [Editing this]

\<TAB\>

* One
* Two
  * [Editing this]

<SHIFT+TAB>
* One
* Two
* [Editing this]

**Comment by KristenEKelly** [comment]
Hello! Is this task still relevant / part of hacktoberfest? If so, I would like to participate and work on this. (Found you on the hacktoberfest discord). It doesn't have the Hacktoberfest label, so not sure.

**Comment by JLambertazzo** [comment]
@KristenEKelly hey! Yes sorry forgot to update this issue, this is still relevant for this year's hacktoberfest 😁

**Comment by sayumimuthu** [comment]
Hi, I'd like to work on this issue.

**Comment by KristenEKelly** [comment]
> I started working on this the other day, can you assign to me :-)

Hi @JLambertazzo I actually have implemented this now and have it working locally :-) I do not have write access however, so I can't commit my code even though I have it on a new branch. Any chance you can give me write access? I think you can block access to the master branch only. Thanks!

**Comment by JLambertazzo** [comment]
Close by PR #59. Big shoutout to @KristenEKelly a first-time contributor to ListExtender! 🚀
